"""empty message

Revision ID: 97cae68e0ba5
Revises: 4050dbe51e95
Create Date: 2024-12-15 23:39:48.294192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97cae68e0ba5'
down_revision = '4050dbe51e95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal_record',
    sa.Column('animal_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('species', sa.String(length=255), nullable=False),
    sa.Column('breed', sa.String(length=255), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=255), nullable=False),
    sa.Column('date_added', sa.Date(), nullable=False),
    sa.Column('disease_history', sa.String(length=255), nullable=False),
    sa.Column('treatement_history', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('animal_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('animal_record')
    # ### end Alembic commands ###
